
/**
 * map for script names against utility objects
 */
export const loadedScripts = new Map()

/**
 * script tags to be generated by the cache method
 */
export let scriptTags = {}


/**
 *
 * @param scripts {Scripts} - An object with all the scripts required.
 * Keys are script names, values are URLs.
 */
export function cache(scripts) {
  Object.entries(scripts).forEach(([script, name]) => {
    const tag = getScript(script, name)
    if (tag) {
      scriptTags = {
        ...scriptTags,
        [name]: {
          name,
          onLoad: onLoad.bind(null, name),
          script,
          tag,
        },
      }
    }
  })
}

export function getScriptStub(name) {
  return scriptTags[name]
}

/**
 * Callback to be fired when each script has loaded.
 * @param name {string} - The name of the string that has just loaded.
 * @param callback {Callback} - A callback to execute when the script has loaded.
 */
export function onLoad(name, callback) {
  const stored = loadedScripts.get(name)

  if (stored && stored.hasLoaded) {
    callback(null, stored)
  } else if (stored) {
    stored.promise.then(() => {
      stored.wasRejected ? callback(stored.error) : callback(null, stored)
    })
  }
}

/**
 * Callback to be fired when all scripts have loaded
 * @param callback {Function} - The callback to be executed.
 */
export function onAllLoad(callback) {
  const promises = []
  const results = []

  console.log('all loaded');

  loadedScripts.forEach((value) => {
    if (value.hasLoaded) {
      results.push(value)
      console.log('loaded:', value);
    } else {
      promises.push(value.promise)
    }
  })

  if (promises.length > 0) {
    Promise.all(promises)
      .then((res) => callback(undefined, res))
      .catch((errs) => callback(errs, undefined))
  } else {
    callback(undefined, results)
  }
}

/**
 * Get a script from a remote location.
 * @param name {string} - The name of the script to be retrieved.
 * @param url {string} - The URL/location of the script to be retrieved.
 */
export function getScript(url, name) {
  if (
    !loadedScripts.has(name) &&
    !document.querySelector(`script[src="${url}"]`)
  ) {
    let tag = document.createElement('script')

    const promise = new Promise((resolve, reject) => {
      const body = document.getElementsByTagName('body')[0]

      // make sure the script type is javascript
      // and that scripts are loaded in order using
      // the "async" option
      tag = {
        ...tag,
        async: false,
        type: 'text/javascript',
      }

      function handleResult(event) {
        const stored = loadedScripts.get(name)

        if (stored) {
          if (event.type === 'load') {
            stored.hasLoaded = true
            resolve(stored)
          } else if (event.type === 'error') {
            stored.wasRejected = true
            reject(stored.error)
          }
        } else {
          reject('Script does not exist')
        }
      }

      // add load and error event listeners
      tag.addEventListener('load', handleResult)
      tag.addEventListener('error', handleResult)

      tag = {
        ...tag,
        src: url,
      }

      body.appendChild(tag)
    })

    const scriptObject = {
      hasLoaded: false,
      promise,
      tag,
      wasRejected: false,
    }

    loadedScripts.set(name, scriptObject)
  }

  return loadedScripts.get(name)
}

// also make cache the default export
export default cache
